//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewExcelInterOp.ManufacturerFactorySvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManufacturerFactorySvc.IManufacturerFactory")]
    public interface IManufacturerFactory {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManufacturerFactory/GetManufacturers", ReplyAction="http://tempuri.org/IManufacturerFactory/GetManufacturersResponse")]
        bool GetManufacturers(out string errorMessage, out NewApp.BusinessTier.Models.Manufacturer[] ManufObjArray, string Manufacturer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManufacturerFactory/GetManufacturersByCriteria", ReplyAction="http://tempuri.org/IManufacturerFactory/GetManufacturersByCriteriaResponse")]
        bool GetManufacturersByCriteria(out string errorMessage, out NewApp.BusinessTier.Models.Manufacturer[] ManufObjArray, string ManufId, string ManufName, string Address, string IDProofTypeId, string IDProofValue, System.DateTime FromDateofBirth, System.DateTime ToDateofBirth, System.DateTime FromDateofStartRelationship, System.DateTime ToDateofStartRelationship, System.DateTime FromDateofExpiryRelationship, System.DateTime ToDateofExpiryRelationship);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManufacturerFactory/GetManufacturerDetails", ReplyAction="http://tempuri.org/IManufacturerFactory/GetManufacturerDetailsResponse")]
        bool GetManufacturerDetails(out string errorMessage, out NewApp.BusinessTier.Models.Manufacturer ManufObj, string Manufacturer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManufacturerFactory/AddManufacturerDetails", ReplyAction="http://tempuri.org/IManufacturerFactory/AddManufacturerDetailsResponse")]
        bool AddManufacturerDetails(out string errorMessage, NewApp.BusinessTier.Models.Manufacturer ManufObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManufacturerFactory/ModifyManufacturerDetails", ReplyAction="http://tempuri.org/IManufacturerFactory/ModifyManufacturerDetailsResponse")]
        void ModifyManufacturerDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManufacturerFactory/DeleteManufacturerDetails", ReplyAction="http://tempuri.org/IManufacturerFactory/DeleteManufacturerDetailsResponse")]
        bool DeleteManufacturerDetails(out string errorMessage, NewApp.BusinessTier.Models.Manufacturer ManufObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManufacturerFactory/AddManufacturerPhoto", ReplyAction="http://tempuri.org/IManufacturerFactory/AddManufacturerPhotoResponse")]
        bool AddManufacturerPhoto(out string errorMessage, int Manufid, NewApp.BusinessTier.Models.Manufacturer ManufObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManufacturerFactory/GetManufacturerPhoto", ReplyAction="http://tempuri.org/IManufacturerFactory/GetManufacturerPhotoResponse")]
        bool GetManufacturerPhoto(out byte[] imgBytes, out string errorMessage, int Manufid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IManufacturerFactoryChannel : NewExcelInterOp.ManufacturerFactorySvc.IManufacturerFactory, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManufacturerFactoryClient : System.ServiceModel.ClientBase<NewExcelInterOp.ManufacturerFactorySvc.IManufacturerFactory>, NewExcelInterOp.ManufacturerFactorySvc.IManufacturerFactory {
        
        public ManufacturerFactoryClient() {
        }
        
        public ManufacturerFactoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManufacturerFactoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManufacturerFactoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManufacturerFactoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GetManufacturers(out string errorMessage, out NewApp.BusinessTier.Models.Manufacturer[] ManufObjArray, string Manufacturer) {
            return base.Channel.GetManufacturers(out errorMessage, out ManufObjArray, Manufacturer);
        }
        
        public bool GetManufacturersByCriteria(out string errorMessage, out NewApp.BusinessTier.Models.Manufacturer[] ManufObjArray, string ManufId, string ManufName, string Address, string IDProofTypeId, string IDProofValue, System.DateTime FromDateofBirth, System.DateTime ToDateofBirth, System.DateTime FromDateofStartRelationship, System.DateTime ToDateofStartRelationship, System.DateTime FromDateofExpiryRelationship, System.DateTime ToDateofExpiryRelationship) {
            return base.Channel.GetManufacturersByCriteria(out errorMessage, out ManufObjArray, ManufId, ManufName, Address, IDProofTypeId, IDProofValue, FromDateofBirth, ToDateofBirth, FromDateofStartRelationship, ToDateofStartRelationship, FromDateofExpiryRelationship, ToDateofExpiryRelationship);
        }
        
        public bool GetManufacturerDetails(out string errorMessage, out NewApp.BusinessTier.Models.Manufacturer ManufObj, string Manufacturer) {
            return base.Channel.GetManufacturerDetails(out errorMessage, out ManufObj, Manufacturer);
        }
        
        public bool AddManufacturerDetails(out string errorMessage, NewApp.BusinessTier.Models.Manufacturer ManufObj) {
            return base.Channel.AddManufacturerDetails(out errorMessage, ManufObj);
        }
        
        public void ModifyManufacturerDetails() {
            base.Channel.ModifyManufacturerDetails();
        }
        
        public bool DeleteManufacturerDetails(out string errorMessage, NewApp.BusinessTier.Models.Manufacturer ManufObj) {
            return base.Channel.DeleteManufacturerDetails(out errorMessage, ManufObj);
        }
        
        public bool AddManufacturerPhoto(out string errorMessage, int Manufid, NewApp.BusinessTier.Models.Manufacturer ManufObj) {
            return base.Channel.AddManufacturerPhoto(out errorMessage, Manufid, ManufObj);
        }
        
        public bool GetManufacturerPhoto(out byte[] imgBytes, out string errorMessage, int Manufid) {
            return base.Channel.GetManufacturerPhoto(out imgBytes, out errorMessage, Manufid);
        }
    }
}
