//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewApp.UserTypeFactorySvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserTypeFactorySvc.IUserTypeFactory")]
    public interface IUserTypeFactory {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserTypeFactory/GetAllUserTypes", ReplyAction="http://tempuri.org/IUserTypeFactory/GetAllUserTypesResponse")]
        bool GetAllUserTypes(out NewApp.BusinessTier.Models.UserType[] UserTypeObjArray, out string errorMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserTypeFactory/GetUserType", ReplyAction="http://tempuri.org/IUserTypeFactory/GetUserTypeResponse")]
        bool GetUserType(out NewApp.BusinessTier.Models.UserType UserType, out string errorMessage, int UserTypeId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserTypeFactoryChannel : NewApp.UserTypeFactorySvc.IUserTypeFactory, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserTypeFactoryClient : System.ServiceModel.ClientBase<NewApp.UserTypeFactorySvc.IUserTypeFactory>, NewApp.UserTypeFactorySvc.IUserTypeFactory {
        
        public UserTypeFactoryClient() {
        }
        
        public UserTypeFactoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserTypeFactoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserTypeFactoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserTypeFactoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GetAllUserTypes(out NewApp.BusinessTier.Models.UserType[] UserTypeObjArray, out string errorMessage) {
            return base.Channel.GetAllUserTypes(out UserTypeObjArray, out errorMessage);
        }
        
        public bool GetUserType(out NewApp.BusinessTier.Models.UserType UserType, out string errorMessage, int UserTypeId) {
            return base.Channel.GetUserType(out UserType, out errorMessage, UserTypeId);
        }
    }
}
