//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewApp.GenderTypeFactorySvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GenderTypeFactorySvc.IGenderTypeFactory")]
    public interface IGenderTypeFactory {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenderTypeFactory/GetAllGenderTypes", ReplyAction="http://tempuri.org/IGenderTypeFactory/GetAllGenderTypesResponse")]
        bool GetAllGenderTypes(out NewApp.BusinessTier.Models.GenderType[] GenderTypeObjArray, out string errorMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenderTypeFactory/GetGenderType", ReplyAction="http://tempuri.org/IGenderTypeFactory/GetGenderTypeResponse")]
        bool GetGenderType(out NewApp.BusinessTier.Models.GenderType GenderType, out string errorMessage, int GenderTypeId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGenderTypeFactoryChannel : NewApp.GenderTypeFactorySvc.IGenderTypeFactory, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GenderTypeFactoryClient : System.ServiceModel.ClientBase<NewApp.GenderTypeFactorySvc.IGenderTypeFactory>, NewApp.GenderTypeFactorySvc.IGenderTypeFactory {
        
        public GenderTypeFactoryClient() {
        }
        
        public GenderTypeFactoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GenderTypeFactoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenderTypeFactoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenderTypeFactoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GetAllGenderTypes(out NewApp.BusinessTier.Models.GenderType[] GenderTypeObjArray, out string errorMessage) {
            return base.Channel.GetAllGenderTypes(out GenderTypeObjArray, out errorMessage);
        }
        
        public bool GetGenderType(out NewApp.BusinessTier.Models.GenderType GenderType, out string errorMessage, int GenderTypeId) {
            return base.Channel.GetGenderType(out GenderType, out errorMessage, GenderTypeId);
        }
    }
}
