//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewApp.ManufacturerStatusFactorySvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManufacturerStatusFactorySvc.IManufacturerStatusFactory")]
    public interface IManufacturerStatusFactory {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManufacturerStatusFactory/GetAllManufacturerStatus", ReplyAction="http://tempuri.org/IManufacturerStatusFactory/GetAllManufacturerStatusResponse")]
        bool GetAllManufacturerStatus(out NewApp.BusinessTier.Models.ManufacturerStatus[] ManufacturerStatusObjArray, out string errorMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManufacturerStatusFactory/GetManufacturerStatus", ReplyAction="http://tempuri.org/IManufacturerStatusFactory/GetManufacturerStatusResponse")]
        bool GetManufacturerStatus(out NewApp.BusinessTier.Models.ManufacturerStatus MyManufStatus, out string errorMessage, int ManufacturerStatusId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IManufacturerStatusFactoryChannel : NewApp.ManufacturerStatusFactorySvc.IManufacturerStatusFactory, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManufacturerStatusFactoryClient : System.ServiceModel.ClientBase<NewApp.ManufacturerStatusFactorySvc.IManufacturerStatusFactory>, NewApp.ManufacturerStatusFactorySvc.IManufacturerStatusFactory {
        
        public ManufacturerStatusFactoryClient() {
        }
        
        public ManufacturerStatusFactoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManufacturerStatusFactoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManufacturerStatusFactoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManufacturerStatusFactoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GetAllManufacturerStatus(out NewApp.BusinessTier.Models.ManufacturerStatus[] ManufacturerStatusObjArray, out string errorMessage) {
            return base.Channel.GetAllManufacturerStatus(out ManufacturerStatusObjArray, out errorMessage);
        }
        
        public bool GetManufacturerStatus(out NewApp.BusinessTier.Models.ManufacturerStatus MyManufStatus, out string errorMessage, int ManufacturerStatusId) {
            return base.Channel.GetManufacturerStatus(out MyManufStatus, out errorMessage, ManufacturerStatusId);
        }
    }
}
