//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewApp.CustomerStatusFactorySvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerStatusFactorySvc.ICustomerStatusFactory")]
    public interface ICustomerStatusFactory {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerStatusFactory/GetAllCustomerStatus", ReplyAction="http://tempuri.org/ICustomerStatusFactory/GetAllCustomerStatusResponse")]
        bool GetAllCustomerStatus(out NewApp.BusinessTier.Models.CustomerStatus[] CustomerStatusObjArray, out string errorMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerStatusFactory/GetCustomerStatus", ReplyAction="http://tempuri.org/ICustomerStatusFactory/GetCustomerStatusResponse")]
        bool GetCustomerStatus(out NewApp.BusinessTier.Models.CustomerStatus CustomerStatus, out string errorMessage, int CustomerStatusId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerStatusFactoryChannel : NewApp.CustomerStatusFactorySvc.ICustomerStatusFactory, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerStatusFactoryClient : System.ServiceModel.ClientBase<NewApp.CustomerStatusFactorySvc.ICustomerStatusFactory>, NewApp.CustomerStatusFactorySvc.ICustomerStatusFactory {
        
        public CustomerStatusFactoryClient() {
        }
        
        public CustomerStatusFactoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerStatusFactoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerStatusFactoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerStatusFactoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GetAllCustomerStatus(out NewApp.BusinessTier.Models.CustomerStatus[] CustomerStatusObjArray, out string errorMessage) {
            return base.Channel.GetAllCustomerStatus(out CustomerStatusObjArray, out errorMessage);
        }
        
        public bool GetCustomerStatus(out NewApp.BusinessTier.Models.CustomerStatus CustomerStatus, out string errorMessage, int CustomerStatusId) {
            return base.Channel.GetCustomerStatus(out CustomerStatus, out errorMessage, CustomerStatusId);
        }
    }
}
