//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewApp.CustomerTypeFactorySvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerTypeFactorySvc.ICustomerTypeFactory")]
    public interface ICustomerTypeFactory {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerTypeFactory/GetAllCustomerTypes", ReplyAction="http://tempuri.org/ICustomerTypeFactory/GetAllCustomerTypesResponse")]
        bool GetAllCustomerTypes(out NewApp.BusinessTier.Models.CustomerType[] CustomerTypeObjArray, out string errorMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerTypeFactory/GetCustomerType", ReplyAction="http://tempuri.org/ICustomerTypeFactory/GetCustomerTypeResponse")]
        bool GetCustomerType(out NewApp.BusinessTier.Models.CustomerType CustomerType, out string errorMessage, int CustomerTypeId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerTypeFactoryChannel : NewApp.CustomerTypeFactorySvc.ICustomerTypeFactory, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerTypeFactoryClient : System.ServiceModel.ClientBase<NewApp.CustomerTypeFactorySvc.ICustomerTypeFactory>, NewApp.CustomerTypeFactorySvc.ICustomerTypeFactory {
        
        public CustomerTypeFactoryClient() {
        }
        
        public CustomerTypeFactoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerTypeFactoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerTypeFactoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerTypeFactoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GetAllCustomerTypes(out NewApp.BusinessTier.Models.CustomerType[] CustomerTypeObjArray, out string errorMessage) {
            return base.Channel.GetAllCustomerTypes(out CustomerTypeObjArray, out errorMessage);
        }
        
        public bool GetCustomerType(out NewApp.BusinessTier.Models.CustomerType CustomerType, out string errorMessage, int CustomerTypeId) {
            return base.Channel.GetCustomerType(out CustomerType, out errorMessage, CustomerTypeId);
        }
    }
}
