//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewApp.SaleFactorySvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SaleFactorySvc.ISaleFactory")]
    public interface ISaleFactory {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleFactory/GetNewSaleId", ReplyAction="http://tempuri.org/ISaleFactory/GetNewSaleIdResponse")]
        bool GetNewSaleId(out string Sale_Id, out string errorMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleFactory/CreateSale", ReplyAction="http://tempuri.org/ISaleFactory/CreateSaleResponse")]
        bool CreateSale(out string errorMessage, NewApp.BusinessTier.Models.Sale Sale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleFactory/GetSaleDetails", ReplyAction="http://tempuri.org/ISaleFactory/GetSaleDetailsResponse")]
        bool GetSaleDetails(out NewApp.BusinessTier.Models.Sale[] SaleObjArray, out string errorMessage, string SalesId, string CustId, string CustName, System.DateTime StartDateOfSale, System.DateTime EndDateOfSale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleFactory/GetUserSaleDetails", ReplyAction="http://tempuri.org/ISaleFactory/GetUserSaleDetailsResponse")]
        bool GetUserSaleDetails(out NewApp.BusinessTier.Models.Sale[] SaleObjArray, out string errorMessage, string SalesId, string UserId, string UserName, System.DateTime StartDateOfSale, System.DateTime EndDateOfSale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleFactory/SearchSaleDetails", ReplyAction="http://tempuri.org/ISaleFactory/SearchSaleDetailsResponse")]
        bool SearchSaleDetails(out NewApp.BusinessTier.Models.Sale[] SaleObjArray, out string errorMessage, string SalesId, string CustId, string CustName, System.DateTime StartDateOfSale, System.DateTime EndDateOfSale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleFactory/ComputeSaleAmounts", ReplyAction="http://tempuri.org/ISaleFactory/ComputeSaleAmountsResponse")]
        bool ComputeSaleAmounts(out NewApp.BusinessTier.Models.Sale NewSaleObj, out string errorMessage, NewApp.BusinessTier.Models.Sale SaleObj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISaleFactoryChannel : NewApp.SaleFactorySvc.ISaleFactory, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaleFactoryClient : System.ServiceModel.ClientBase<NewApp.SaleFactorySvc.ISaleFactory>, NewApp.SaleFactorySvc.ISaleFactory {
        
        public SaleFactoryClient() {
        }
        
        public SaleFactoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SaleFactoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaleFactoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaleFactoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GetNewSaleId(out string Sale_Id, out string errorMessage) {
            return base.Channel.GetNewSaleId(out Sale_Id, out errorMessage);
        }
        
        public bool CreateSale(out string errorMessage, NewApp.BusinessTier.Models.Sale Sale) {
            return base.Channel.CreateSale(out errorMessage, Sale);
        }
        
        public bool GetSaleDetails(out NewApp.BusinessTier.Models.Sale[] SaleObjArray, out string errorMessage, string SalesId, string CustId, string CustName, System.DateTime StartDateOfSale, System.DateTime EndDateOfSale) {
            return base.Channel.GetSaleDetails(out SaleObjArray, out errorMessage, SalesId, CustId, CustName, StartDateOfSale, EndDateOfSale);
        }
        
        public bool GetUserSaleDetails(out NewApp.BusinessTier.Models.Sale[] SaleObjArray, out string errorMessage, string SalesId, string UserId, string UserName, System.DateTime StartDateOfSale, System.DateTime EndDateOfSale) {
            return base.Channel.GetUserSaleDetails(out SaleObjArray, out errorMessage, SalesId, UserId, UserName, StartDateOfSale, EndDateOfSale);
        }
        
        public bool SearchSaleDetails(out NewApp.BusinessTier.Models.Sale[] SaleObjArray, out string errorMessage, string SalesId, string CustId, string CustName, System.DateTime StartDateOfSale, System.DateTime EndDateOfSale) {
            return base.Channel.SearchSaleDetails(out SaleObjArray, out errorMessage, SalesId, CustId, CustName, StartDateOfSale, EndDateOfSale);
        }
        
        public bool ComputeSaleAmounts(out NewApp.BusinessTier.Models.Sale NewSaleObj, out string errorMessage, NewApp.BusinessTier.Models.Sale SaleObj) {
            return base.Channel.ComputeSaleAmounts(out NewSaleObj, out errorMessage, SaleObj);
        }
    }
}
