//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewApp.TaxItemFactorySvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TaxItemFactorySvc.ITaxItemFactory")]
    public interface ITaxItemFactory {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxItemFactory/GetTaxItemList", ReplyAction="http://tempuri.org/ITaxItemFactory/GetTaxItemListResponse")]
        bool GetTaxItemList(out string errorMessage, out NewApp.BusinessTier.Models.TaxItem[] TaxItemObjArray, string TaxCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxItemFactory/AddItemToTaxCode", ReplyAction="http://tempuri.org/ITaxItemFactory/AddItemToTaxCodeResponse")]
        bool AddItemToTaxCode(out string errorMessage, NewApp.BusinessTier.Models.TaxItem TaxItemObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxItemFactory/ModifyTaxItemDetails", ReplyAction="http://tempuri.org/ITaxItemFactory/ModifyTaxItemDetailsResponse")]
        void ModifyTaxItemDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxItemFactory/DeleteTaxItemDetails", ReplyAction="http://tempuri.org/ITaxItemFactory/DeleteTaxItemDetailsResponse")]
        bool DeleteTaxItemDetails(out string errorMessage, NewApp.BusinessTier.Models.TaxItem TaxItemObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxItemFactory/GetItemsNotLnkdToSpecificTaxCode", ReplyAction="http://tempuri.org/ITaxItemFactory/GetItemsNotLnkdToSpecificTaxCodeResponse")]
        bool GetItemsNotLnkdToSpecificTaxCode(out System.Data.DataTable ItemBatchList, out string errorMessage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITaxItemFactoryChannel : NewApp.TaxItemFactorySvc.ITaxItemFactory, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaxItemFactoryClient : System.ServiceModel.ClientBase<NewApp.TaxItemFactorySvc.ITaxItemFactory>, NewApp.TaxItemFactorySvc.ITaxItemFactory {
        
        public TaxItemFactoryClient() {
        }
        
        public TaxItemFactoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaxItemFactoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaxItemFactoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaxItemFactoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GetTaxItemList(out string errorMessage, out NewApp.BusinessTier.Models.TaxItem[] TaxItemObjArray, string TaxCode) {
            return base.Channel.GetTaxItemList(out errorMessage, out TaxItemObjArray, TaxCode);
        }
        
        public bool AddItemToTaxCode(out string errorMessage, NewApp.BusinessTier.Models.TaxItem TaxItemObj) {
            return base.Channel.AddItemToTaxCode(out errorMessage, TaxItemObj);
        }
        
        public void ModifyTaxItemDetails() {
            base.Channel.ModifyTaxItemDetails();
        }
        
        public bool DeleteTaxItemDetails(out string errorMessage, NewApp.BusinessTier.Models.TaxItem TaxItemObj) {
            return base.Channel.DeleteTaxItemDetails(out errorMessage, TaxItemObj);
        }
        
        public bool GetItemsNotLnkdToSpecificTaxCode(out System.Data.DataTable ItemBatchList, out string errorMessage) {
            return base.Channel.GetItemsNotLnkdToSpecificTaxCode(out ItemBatchList, out errorMessage);
        }
    }
}
