//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewApp.SaleItemFactorySvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SaleItemFactorySvc.ISaleItemFactory")]
    public interface ISaleItemFactory {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleItemFactory/GetSaleItems", ReplyAction="http://tempuri.org/ISaleItemFactory/GetSaleItemsResponse")]
        bool GetSaleItems(out NewApp.BusinessTier.Models.SaleItem[] SaleItemObjArray, out string errorMessage, string SaleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleItemFactory/ComputeSaleItemAmounts", ReplyAction="http://tempuri.org/ISaleItemFactory/ComputeSaleItemAmountsResponse")]
        bool ComputeSaleItemAmounts(out NewApp.BusinessTier.Models.SaleItem NewSaleItemObj, out string errorMessage, NewApp.BusinessTier.Models.SaleItem SaleItemObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleItemFactory/UpdateQuantity", ReplyAction="http://tempuri.org/ISaleItemFactory/UpdateQuantityResponse")]
        bool UpdateQuantity(out string errorMessage, string SaleId, int SerialNumb, string ItemId, string BatchId, int Quantity, char Operation);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISaleItemFactoryChannel : NewApp.SaleItemFactorySvc.ISaleItemFactory, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaleItemFactoryClient : System.ServiceModel.ClientBase<NewApp.SaleItemFactorySvc.ISaleItemFactory>, NewApp.SaleItemFactorySvc.ISaleItemFactory {
        
        public SaleItemFactoryClient() {
        }
        
        public SaleItemFactoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SaleItemFactoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaleItemFactoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaleItemFactoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GetSaleItems(out NewApp.BusinessTier.Models.SaleItem[] SaleItemObjArray, out string errorMessage, string SaleId) {
            return base.Channel.GetSaleItems(out SaleItemObjArray, out errorMessage, SaleId);
        }
        
        public bool ComputeSaleItemAmounts(out NewApp.BusinessTier.Models.SaleItem NewSaleItemObj, out string errorMessage, NewApp.BusinessTier.Models.SaleItem SaleItemObj) {
            return base.Channel.ComputeSaleItemAmounts(out NewSaleItemObj, out errorMessage, SaleItemObj);
        }
        
        public bool UpdateQuantity(out string errorMessage, string SaleId, int SerialNumb, string ItemId, string BatchId, int Quantity, char Operation) {
            return base.Channel.UpdateQuantity(out errorMessage, SaleId, SerialNumb, ItemId, BatchId, Quantity, Operation);
        }
    }
}
