//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewApp.TaxFactorySvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TaxFactorySvc.ITaxFactory")]
    public interface ITaxFactory {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxFactory/GetTaxDetails", ReplyAction="http://tempuri.org/ITaxFactory/GetTaxDetailsResponse")]
        bool GetTaxDetails(out string errorMessage, out NewApp.BusinessTier.Models.Tax TaxObj, string TaxCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxFactory/GetTaxList", ReplyAction="http://tempuri.org/ITaxFactory/GetTaxListResponse")]
        bool GetTaxList(out string errorMessage, out NewApp.BusinessTier.Models.Tax[] TaxObjArray, string TaxCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxFactory/GetGlobalTaxesList", ReplyAction="http://tempuri.org/ITaxFactory/GetGlobalTaxesListResponse")]
        bool GetGlobalTaxesList(out string errorMessage, out NewApp.BusinessTier.Models.Tax[] TaxObjArray);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxFactory/AddNewTax", ReplyAction="http://tempuri.org/ITaxFactory/AddNewTaxResponse")]
        bool AddNewTax(out string errorMessage, NewApp.BusinessTier.Models.Tax TaxObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxFactory/ModifyTaxDetails", ReplyAction="http://tempuri.org/ITaxFactory/ModifyTaxDetailsResponse")]
        void ModifyTaxDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxFactory/DeleteTaxDetails", ReplyAction="http://tempuri.org/ITaxFactory/DeleteTaxDetailsResponse")]
        bool DeleteTaxDetails(out string errorMessage, NewApp.BusinessTier.Models.Tax TaxObj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITaxFactoryChannel : NewApp.TaxFactorySvc.ITaxFactory, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaxFactoryClient : System.ServiceModel.ClientBase<NewApp.TaxFactorySvc.ITaxFactory>, NewApp.TaxFactorySvc.ITaxFactory {
        
        public TaxFactoryClient() {
        }
        
        public TaxFactoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaxFactoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaxFactoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaxFactoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GetTaxDetails(out string errorMessage, out NewApp.BusinessTier.Models.Tax TaxObj, string TaxCode) {
            return base.Channel.GetTaxDetails(out errorMessage, out TaxObj, TaxCode);
        }
        
        public bool GetTaxList(out string errorMessage, out NewApp.BusinessTier.Models.Tax[] TaxObjArray, string TaxCode) {
            return base.Channel.GetTaxList(out errorMessage, out TaxObjArray, TaxCode);
        }
        
        public bool GetGlobalTaxesList(out string errorMessage, out NewApp.BusinessTier.Models.Tax[] TaxObjArray) {
            return base.Channel.GetGlobalTaxesList(out errorMessage, out TaxObjArray);
        }
        
        public bool AddNewTax(out string errorMessage, NewApp.BusinessTier.Models.Tax TaxObj) {
            return base.Channel.AddNewTax(out errorMessage, TaxObj);
        }
        
        public void ModifyTaxDetails() {
            base.Channel.ModifyTaxDetails();
        }
        
        public bool DeleteTaxDetails(out string errorMessage, NewApp.BusinessTier.Models.Tax TaxObj) {
            return base.Channel.DeleteTaxDetails(out errorMessage, TaxObj);
        }
    }
}
