//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewApp.TaxKindFactorySvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TaxKindFactorySvc.ITaxKindFactory")]
    public interface ITaxKindFactory {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxKindFactory/GetAllTaxKinds", ReplyAction="http://tempuri.org/ITaxKindFactory/GetAllTaxKindsResponse")]
        bool GetAllTaxKinds(out NewApp.BusinessTier.Models.TaxKind[] TaxKindObjArray, out string errorMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxKindFactory/GetTaxKind", ReplyAction="http://tempuri.org/ITaxKindFactory/GetTaxKindResponse")]
        bool GetTaxKind(out NewApp.BusinessTier.Models.TaxKind TaxKind, out string errorMessage, int TaxKindId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITaxKindFactoryChannel : NewApp.TaxKindFactorySvc.ITaxKindFactory, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaxKindFactoryClient : System.ServiceModel.ClientBase<NewApp.TaxKindFactorySvc.ITaxKindFactory>, NewApp.TaxKindFactorySvc.ITaxKindFactory {
        
        public TaxKindFactoryClient() {
        }
        
        public TaxKindFactoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaxKindFactoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaxKindFactoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaxKindFactoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GetAllTaxKinds(out NewApp.BusinessTier.Models.TaxKind[] TaxKindObjArray, out string errorMessage) {
            return base.Channel.GetAllTaxKinds(out TaxKindObjArray, out errorMessage);
        }
        
        public bool GetTaxKind(out NewApp.BusinessTier.Models.TaxKind TaxKind, out string errorMessage, int TaxKindId) {
            return base.Channel.GetTaxKind(out TaxKind, out errorMessage, TaxKindId);
        }
    }
}
