//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewApp.DiscountFactorySvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DiscountFactorySvc.IDiscountFactory")]
    public interface IDiscountFactory {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscountFactory/GetDiscountDetails", ReplyAction="http://tempuri.org/IDiscountFactory/GetDiscountDetailsResponse")]
        bool GetDiscountDetails(out string errorMessage, out NewApp.BusinessTier.Models.Discount DiscObj, string DiscCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscountFactory/GetDiscountList", ReplyAction="http://tempuri.org/IDiscountFactory/GetDiscountListResponse")]
        bool GetDiscountList(out string errorMessage, out NewApp.BusinessTier.Models.Discount[] DiscObjArray, string DiscCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscountFactory/AddNewDiscount", ReplyAction="http://tempuri.org/IDiscountFactory/AddNewDiscountResponse")]
        bool AddNewDiscount(out string errorMessage, NewApp.BusinessTier.Models.Discount DiscObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscountFactory/ModifyDiscDetails", ReplyAction="http://tempuri.org/IDiscountFactory/ModifyDiscDetailsResponse")]
        void ModifyDiscDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscountFactory/DeleteDiscDetails", ReplyAction="http://tempuri.org/IDiscountFactory/DeleteDiscDetailsResponse")]
        bool DeleteDiscDetails(out string errorMessage, NewApp.BusinessTier.Models.Discount DiscObj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDiscountFactoryChannel : NewApp.DiscountFactorySvc.IDiscountFactory, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DiscountFactoryClient : System.ServiceModel.ClientBase<NewApp.DiscountFactorySvc.IDiscountFactory>, NewApp.DiscountFactorySvc.IDiscountFactory {
        
        public DiscountFactoryClient() {
        }
        
        public DiscountFactoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DiscountFactoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiscountFactoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiscountFactoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GetDiscountDetails(out string errorMessage, out NewApp.BusinessTier.Models.Discount DiscObj, string DiscCode) {
            return base.Channel.GetDiscountDetails(out errorMessage, out DiscObj, DiscCode);
        }
        
        public bool GetDiscountList(out string errorMessage, out NewApp.BusinessTier.Models.Discount[] DiscObjArray, string DiscCode) {
            return base.Channel.GetDiscountList(out errorMessage, out DiscObjArray, DiscCode);
        }
        
        public bool AddNewDiscount(out string errorMessage, NewApp.BusinessTier.Models.Discount DiscObj) {
            return base.Channel.AddNewDiscount(out errorMessage, DiscObj);
        }
        
        public void ModifyDiscDetails() {
            base.Channel.ModifyDiscDetails();
        }
        
        public bool DeleteDiscDetails(out string errorMessage, NewApp.BusinessTier.Models.Discount DiscObj) {
            return base.Channel.DeleteDiscDetails(out errorMessage, DiscObj);
        }
    }
}
