//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewApp.DiscountItemFactorySvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DiscountItemFactorySvc.IDiscountItemFactory")]
    public interface IDiscountItemFactory {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscountItemFactory/AddItemToDiscount", ReplyAction="http://tempuri.org/IDiscountItemFactory/AddItemToDiscountResponse")]
        bool AddItemToDiscount(out string errorMessage, NewApp.BusinessTier.Models.DiscountItem DiscItemObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscountItemFactory/ModifyDiscountDetails", ReplyAction="http://tempuri.org/IDiscountItemFactory/ModifyDiscountDetailsResponse")]
        void ModifyDiscountDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscountItemFactory/DeleteDiscountDetails", ReplyAction="http://tempuri.org/IDiscountItemFactory/DeleteDiscountDetailsResponse")]
        bool DeleteDiscountDetails(out string errorMessage, NewApp.BusinessTier.Models.DiscountItem DiscItemObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscountItemFactory/GetItemsNotLnkdToSpecificDiscCode", ReplyAction="http://tempuri.org/IDiscountItemFactory/GetItemsNotLnkdToSpecificDiscCodeResponse" +
            "")]
        bool GetItemsNotLnkdToSpecificDiscCode(out System.Data.DataTable ItemBatchList, out string errorMessage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDiscountItemFactoryChannel : NewApp.DiscountItemFactorySvc.IDiscountItemFactory, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DiscountItemFactoryClient : System.ServiceModel.ClientBase<NewApp.DiscountItemFactorySvc.IDiscountItemFactory>, NewApp.DiscountItemFactorySvc.IDiscountItemFactory {
        
        public DiscountItemFactoryClient() {
        }
        
        public DiscountItemFactoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DiscountItemFactoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiscountItemFactoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiscountItemFactoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddItemToDiscount(out string errorMessage, NewApp.BusinessTier.Models.DiscountItem DiscItemObj) {
            return base.Channel.AddItemToDiscount(out errorMessage, DiscItemObj);
        }
        
        public void ModifyDiscountDetails() {
            base.Channel.ModifyDiscountDetails();
        }
        
        public bool DeleteDiscountDetails(out string errorMessage, NewApp.BusinessTier.Models.DiscountItem DiscItemObj) {
            return base.Channel.DeleteDiscountDetails(out errorMessage, DiscItemObj);
        }
        
        public bool GetItemsNotLnkdToSpecificDiscCode(out System.Data.DataTable ItemBatchList, out string errorMessage) {
            return base.Channel.GetItemsNotLnkdToSpecificDiscCode(out ItemBatchList, out errorMessage);
        }
    }
}
