USE [master]
GO
/****** Object:  Database [NewAppDb]    Script Date: 04/16/2015 18:34:24 ******/
CREATE DATABASE [NewAppDb] ON  PRIMARY 
( NAME = N'NewAppDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\NewAppDb.mdf' , SIZE = 3328KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'NewAppDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\NewAppDb_log.LDF' , SIZE = 768KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [NewAppDb] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NewAppDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [NewAppDb] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [NewAppDb] SET ANSI_NULLS OFF
GO
ALTER DATABASE [NewAppDb] SET ANSI_PADDING OFF
GO
ALTER DATABASE [NewAppDb] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [NewAppDb] SET ARITHABORT OFF
GO
ALTER DATABASE [NewAppDb] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [NewAppDb] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [NewAppDb] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [NewAppDb] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [NewAppDb] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [NewAppDb] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [NewAppDb] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [NewAppDb] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [NewAppDb] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [NewAppDb] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [NewAppDb] SET  DISABLE_BROKER
GO
ALTER DATABASE [NewAppDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [NewAppDb] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [NewAppDb] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [NewAppDb] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [NewAppDb] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [NewAppDb] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [NewAppDb] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [NewAppDb] SET  READ_WRITE
GO
ALTER DATABASE [NewAppDb] SET RECOVERY SIMPLE
GO
ALTER DATABASE [NewAppDb] SET  MULTI_USER
GO
ALTER DATABASE [NewAppDb] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [NewAppDb] SET DB_CHAINING OFF
GO
