//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewExcelInterOp.StoreItemFactorySvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StoreItemFactorySvc.IStoreItemFactory")]
    public interface IStoreItemFactory {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreItemFactory/AddStoreItem", ReplyAction="http://tempuri.org/IStoreItemFactory/AddStoreItemResponse")]
        bool AddStoreItem(out string errorMessage, NewApp.BusinessTier.Models.StoreItem StoreItemObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreItemFactory/ModifyStoreItem", ReplyAction="http://tempuri.org/IStoreItemFactory/ModifyStoreItemResponse")]
        bool ModifyStoreItem(out string errorMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreItemFactory/DeleteStoreItem", ReplyAction="http://tempuri.org/IStoreItemFactory/DeleteStoreItemResponse")]
        bool DeleteStoreItem(out string errorMessage, NewApp.BusinessTier.Models.StoreItem StoreItemObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreItemFactory/DeleteStoreItemBatch", ReplyAction="http://tempuri.org/IStoreItemFactory/DeleteStoreItemBatchResponse")]
        bool DeleteStoreItemBatch(out string errorMessage, NewApp.BusinessTier.Models.StoreItem StoreItemObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreItemFactory/GetStoreItemByCriteria", ReplyAction="http://tempuri.org/IStoreItemFactory/GetStoreItemByCriteriaResponse")]
        bool GetStoreItemByCriteria(out string errorMessage, out NewApp.BusinessTier.Models.StoreItem[] StoreItemObjArray, string ItemId, string ItemName, string BatchId, System.DateTime StartDateOfManuf, System.DateTime EndDateOfManuf, System.DateTime StartDateOfExp, System.DateTime EndDateOfExp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreItemFactory/GetStoreItemByItemIdOrName", ReplyAction="http://tempuri.org/IStoreItemFactory/GetStoreItemByItemIdOrNameResponse")]
        bool GetStoreItemByItemIdOrName(out string errorMessage, out NewApp.BusinessTier.Models.StoreItem[] StoreItemObjArray, string ItemIdOrName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStoreItemFactoryChannel : NewExcelInterOp.StoreItemFactorySvc.IStoreItemFactory, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StoreItemFactoryClient : System.ServiceModel.ClientBase<NewExcelInterOp.StoreItemFactorySvc.IStoreItemFactory>, NewExcelInterOp.StoreItemFactorySvc.IStoreItemFactory {
        
        public StoreItemFactoryClient() {
        }
        
        public StoreItemFactoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StoreItemFactoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreItemFactoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreItemFactoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddStoreItem(out string errorMessage, NewApp.BusinessTier.Models.StoreItem StoreItemObj) {
            return base.Channel.AddStoreItem(out errorMessage, StoreItemObj);
        }
        
        public bool ModifyStoreItem(out string errorMessage) {
            return base.Channel.ModifyStoreItem(out errorMessage);
        }
        
        public bool DeleteStoreItem(out string errorMessage, NewApp.BusinessTier.Models.StoreItem StoreItemObj) {
            return base.Channel.DeleteStoreItem(out errorMessage, StoreItemObj);
        }
        
        public bool DeleteStoreItemBatch(out string errorMessage, NewApp.BusinessTier.Models.StoreItem StoreItemObj) {
            return base.Channel.DeleteStoreItemBatch(out errorMessage, StoreItemObj);
        }
        
        public bool GetStoreItemByCriteria(out string errorMessage, out NewApp.BusinessTier.Models.StoreItem[] StoreItemObjArray, string ItemId, string ItemName, string BatchId, System.DateTime StartDateOfManuf, System.DateTime EndDateOfManuf, System.DateTime StartDateOfExp, System.DateTime EndDateOfExp) {
            return base.Channel.GetStoreItemByCriteria(out errorMessage, out StoreItemObjArray, ItemId, ItemName, BatchId, StartDateOfManuf, EndDateOfManuf, StartDateOfExp, EndDateOfExp);
        }
        
        public bool GetStoreItemByItemIdOrName(out string errorMessage, out NewApp.BusinessTier.Models.StoreItem[] StoreItemObjArray, string ItemIdOrName) {
            return base.Channel.GetStoreItemByItemIdOrName(out errorMessage, out StoreItemObjArray, ItemIdOrName);
        }
    }
}
