//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewApp.DiscountTypeFactorySvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DiscountTypeFactorySvc.IDiscountTypeFactory")]
    public interface IDiscountTypeFactory {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscountTypeFactory/GetAllDiscountTypes", ReplyAction="http://tempuri.org/IDiscountTypeFactory/GetAllDiscountTypesResponse")]
        bool GetAllDiscountTypes(out NewApp.BusinessTier.Models.DiscountType[] DiscountTypeObjArray, out string errorMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscountTypeFactory/GetDiscountType", ReplyAction="http://tempuri.org/IDiscountTypeFactory/GetDiscountTypeResponse")]
        bool GetDiscountType(out NewApp.BusinessTier.Models.DiscountType DiscountType, out string errorMessage, int DiscountTypeId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDiscountTypeFactoryChannel : NewApp.DiscountTypeFactorySvc.IDiscountTypeFactory, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DiscountTypeFactoryClient : System.ServiceModel.ClientBase<NewApp.DiscountTypeFactorySvc.IDiscountTypeFactory>, NewApp.DiscountTypeFactorySvc.IDiscountTypeFactory {
        
        public DiscountTypeFactoryClient() {
        }
        
        public DiscountTypeFactoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DiscountTypeFactoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiscountTypeFactoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiscountTypeFactoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GetAllDiscountTypes(out NewApp.BusinessTier.Models.DiscountType[] DiscountTypeObjArray, out string errorMessage) {
            return base.Channel.GetAllDiscountTypes(out DiscountTypeObjArray, out errorMessage);
        }
        
        public bool GetDiscountType(out NewApp.BusinessTier.Models.DiscountType DiscountType, out string errorMessage, int DiscountTypeId) {
            return base.Channel.GetDiscountType(out DiscountType, out errorMessage, DiscountTypeId);
        }
    }
}
