//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewApp.VendorStatusFactorySvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VendorStatusFactorySvc.IVendorStatusFactory")]
    public interface IVendorStatusFactory {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorStatusFactory/GetAllVendorStatus", ReplyAction="http://tempuri.org/IVendorStatusFactory/GetAllVendorStatusResponse")]
        bool GetAllVendorStatus(out NewApp.BusinessTier.Models.VendorStatus[] VendorStatusObjArray, out string errorMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorStatusFactory/GetVendorStatus", ReplyAction="http://tempuri.org/IVendorStatusFactory/GetVendorStatusResponse")]
        bool GetVendorStatus(out NewApp.BusinessTier.Models.VendorStatus VendorStatus, out string errorMessage, int VendorStatusId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVendorStatusFactoryChannel : NewApp.VendorStatusFactorySvc.IVendorStatusFactory, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VendorStatusFactoryClient : System.ServiceModel.ClientBase<NewApp.VendorStatusFactorySvc.IVendorStatusFactory>, NewApp.VendorStatusFactorySvc.IVendorStatusFactory {
        
        public VendorStatusFactoryClient() {
        }
        
        public VendorStatusFactoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VendorStatusFactoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VendorStatusFactoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VendorStatusFactoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GetAllVendorStatus(out NewApp.BusinessTier.Models.VendorStatus[] VendorStatusObjArray, out string errorMessage) {
            return base.Channel.GetAllVendorStatus(out VendorStatusObjArray, out errorMessage);
        }
        
        public bool GetVendorStatus(out NewApp.BusinessTier.Models.VendorStatus VendorStatus, out string errorMessage, int VendorStatusId) {
            return base.Channel.GetVendorStatus(out VendorStatus, out errorMessage, VendorStatusId);
        }
    }
}
