//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewApp.CustomerFactorySvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerFactorySvc.ICustomerFactory")]
    public interface ICustomerFactory {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerFactory/GetCustomers", ReplyAction="http://tempuri.org/ICustomerFactory/GetCustomersResponse")]
        bool GetCustomers(out string errorMessage, out NewApp.BusinessTier.Models.Customer[] CustObjArray, string CustomerIdOrName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerFactory/GetCustomersByCriteria", ReplyAction="http://tempuri.org/ICustomerFactory/GetCustomersByCriteriaResponse")]
        bool GetCustomersByCriteria(out string errorMessage, out NewApp.BusinessTier.Models.Customer[] CustObjArray, string CustId, string CustName, string Address, int IDProofTypeId, string IDProofValue, System.DateTime FromDateofBirth, System.DateTime ToDateofBirth, System.DateTime FromDateofStartRelationship, System.DateTime ToDateofStartRelationship, System.DateTime FromDateofExpiryRelationship, System.DateTime ToDateofExpiryRelationship);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerFactory/GetCustomerDetails", ReplyAction="http://tempuri.org/ICustomerFactory/GetCustomerDetailsResponse")]
        bool GetCustomerDetails(out string errorMessage, out NewApp.BusinessTier.Models.Customer CustObj, string CustomerIdOrName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerFactory/GetCustomerBasicDetails", ReplyAction="http://tempuri.org/ICustomerFactory/GetCustomerBasicDetailsResponse")]
        bool GetCustomerBasicDetails(out string errorMessage, out NewApp.BusinessTier.Models.Customer CustObj, string CustomerIdOrName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerFactory/AddCustomerDetails", ReplyAction="http://tempuri.org/ICustomerFactory/AddCustomerDetailsResponse")]
        bool AddCustomerDetails(out string errorMessage, NewApp.BusinessTier.Models.Customer CustObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerFactory/ModifyCustomerDetails", ReplyAction="http://tempuri.org/ICustomerFactory/ModifyCustomerDetailsResponse")]
        void ModifyCustomerDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerFactory/DeleteCustomerDetails", ReplyAction="http://tempuri.org/ICustomerFactory/DeleteCustomerDetailsResponse")]
        bool DeleteCustomerDetails(out string errorMessage, NewApp.BusinessTier.Models.Customer CustObj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerFactoryChannel : NewApp.CustomerFactorySvc.ICustomerFactory, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerFactoryClient : System.ServiceModel.ClientBase<NewApp.CustomerFactorySvc.ICustomerFactory>, NewApp.CustomerFactorySvc.ICustomerFactory {
        
        public CustomerFactoryClient() {
        }
        
        public CustomerFactoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerFactoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerFactoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerFactoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GetCustomers(out string errorMessage, out NewApp.BusinessTier.Models.Customer[] CustObjArray, string CustomerIdOrName) {
            return base.Channel.GetCustomers(out errorMessage, out CustObjArray, CustomerIdOrName);
        }
        
        public bool GetCustomersByCriteria(out string errorMessage, out NewApp.BusinessTier.Models.Customer[] CustObjArray, string CustId, string CustName, string Address, int IDProofTypeId, string IDProofValue, System.DateTime FromDateofBirth, System.DateTime ToDateofBirth, System.DateTime FromDateofStartRelationship, System.DateTime ToDateofStartRelationship, System.DateTime FromDateofExpiryRelationship, System.DateTime ToDateofExpiryRelationship) {
            return base.Channel.GetCustomersByCriteria(out errorMessage, out CustObjArray, CustId, CustName, Address, IDProofTypeId, IDProofValue, FromDateofBirth, ToDateofBirth, FromDateofStartRelationship, ToDateofStartRelationship, FromDateofExpiryRelationship, ToDateofExpiryRelationship);
        }
        
        public bool GetCustomerDetails(out string errorMessage, out NewApp.BusinessTier.Models.Customer CustObj, string CustomerIdOrName) {
            return base.Channel.GetCustomerDetails(out errorMessage, out CustObj, CustomerIdOrName);
        }
        
        public bool GetCustomerBasicDetails(out string errorMessage, out NewApp.BusinessTier.Models.Customer CustObj, string CustomerIdOrName) {
            return base.Channel.GetCustomerBasicDetails(out errorMessage, out CustObj, CustomerIdOrName);
        }
        
        public bool AddCustomerDetails(out string errorMessage, NewApp.BusinessTier.Models.Customer CustObj) {
            return base.Channel.AddCustomerDetails(out errorMessage, CustObj);
        }
        
        public void ModifyCustomerDetails() {
            base.Channel.ModifyCustomerDetails();
        }
        
        public bool DeleteCustomerDetails(out string errorMessage, NewApp.BusinessTier.Models.Customer CustObj) {
            return base.Channel.DeleteCustomerDetails(out errorMessage, CustObj);
        }
    }
}
