//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewApp.VendorFactorySvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VendorFactorySvc.IVendorFactory")]
    public interface IVendorFactory {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorFactory/GetVendors", ReplyAction="http://tempuri.org/IVendorFactory/GetVendorsResponse")]
        bool GetVendors(out string errorMessage, out NewApp.BusinessTier.Models.Vendor[] VendorObjArray, string Vendor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorFactory/GetVendorsByCriteria", ReplyAction="http://tempuri.org/IVendorFactory/GetVendorsByCriteriaResponse")]
        bool GetVendorsByCriteria(out string errorMessage, out NewApp.BusinessTier.Models.Vendor[] VendorObjArray, string VendorId, string VendorName, string Address, string IDProofTypeId, string IDProofValue, System.DateTime FromDateofBirth, System.DateTime ToDateofBirth, System.DateTime FromDateofStartRelationship, System.DateTime ToDateofStartRelationship, System.DateTime FromDateofExpiryRelationship, System.DateTime ToDateofExpiryRelationship);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorFactory/GetVendorDetails", ReplyAction="http://tempuri.org/IVendorFactory/GetVendorDetailsResponse")]
        bool GetVendorDetails(out string errorMessage, out NewApp.BusinessTier.Models.Vendor VendorObj, string Vendor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorFactory/AddVendorDetails", ReplyAction="http://tempuri.org/IVendorFactory/AddVendorDetailsResponse")]
        bool AddVendorDetails(out string errorMessage, NewApp.BusinessTier.Models.Vendor VendorObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorFactory/ModifyVendorDetails", ReplyAction="http://tempuri.org/IVendorFactory/ModifyVendorDetailsResponse")]
        void ModifyVendorDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorFactory/DeleteVendorDetails", ReplyAction="http://tempuri.org/IVendorFactory/DeleteVendorDetailsResponse")]
        bool DeleteVendorDetails(out string errorMessage, NewApp.BusinessTier.Models.Vendor VendorObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorFactory/AddVendorPhoto", ReplyAction="http://tempuri.org/IVendorFactory/AddVendorPhotoResponse")]
        bool AddVendorPhoto(out string errorMessage, int Vendorid, NewApp.BusinessTier.Models.Vendor VendorObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorFactory/GetVendorPhoto", ReplyAction="http://tempuri.org/IVendorFactory/GetVendorPhotoResponse")]
        bool GetVendorPhoto(out byte[] imgBytes, out string errorMessage, int Vendorid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVendorFactoryChannel : NewApp.VendorFactorySvc.IVendorFactory, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VendorFactoryClient : System.ServiceModel.ClientBase<NewApp.VendorFactorySvc.IVendorFactory>, NewApp.VendorFactorySvc.IVendorFactory {
        
        public VendorFactoryClient() {
        }
        
        public VendorFactoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VendorFactoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VendorFactoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VendorFactoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GetVendors(out string errorMessage, out NewApp.BusinessTier.Models.Vendor[] VendorObjArray, string Vendor) {
            return base.Channel.GetVendors(out errorMessage, out VendorObjArray, Vendor);
        }
        
        public bool GetVendorsByCriteria(out string errorMessage, out NewApp.BusinessTier.Models.Vendor[] VendorObjArray, string VendorId, string VendorName, string Address, string IDProofTypeId, string IDProofValue, System.DateTime FromDateofBirth, System.DateTime ToDateofBirth, System.DateTime FromDateofStartRelationship, System.DateTime ToDateofStartRelationship, System.DateTime FromDateofExpiryRelationship, System.DateTime ToDateofExpiryRelationship) {
            return base.Channel.GetVendorsByCriteria(out errorMessage, out VendorObjArray, VendorId, VendorName, Address, IDProofTypeId, IDProofValue, FromDateofBirth, ToDateofBirth, FromDateofStartRelationship, ToDateofStartRelationship, FromDateofExpiryRelationship, ToDateofExpiryRelationship);
        }
        
        public bool GetVendorDetails(out string errorMessage, out NewApp.BusinessTier.Models.Vendor VendorObj, string Vendor) {
            return base.Channel.GetVendorDetails(out errorMessage, out VendorObj, Vendor);
        }
        
        public bool AddVendorDetails(out string errorMessage, NewApp.BusinessTier.Models.Vendor VendorObj) {
            return base.Channel.AddVendorDetails(out errorMessage, VendorObj);
        }
        
        public void ModifyVendorDetails() {
            base.Channel.ModifyVendorDetails();
        }
        
        public bool DeleteVendorDetails(out string errorMessage, NewApp.BusinessTier.Models.Vendor VendorObj) {
            return base.Channel.DeleteVendorDetails(out errorMessage, VendorObj);
        }
        
        public bool AddVendorPhoto(out string errorMessage, int Vendorid, NewApp.BusinessTier.Models.Vendor VendorObj) {
            return base.Channel.AddVendorPhoto(out errorMessage, Vendorid, VendorObj);
        }
        
        public bool GetVendorPhoto(out byte[] imgBytes, out string errorMessage, int Vendorid) {
            return base.Channel.GetVendorPhoto(out imgBytes, out errorMessage, Vendorid);
        }
    }
}
