//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewApp.DiscountKindFactorySvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DiscountKindFactorySvc.IDiscountKindFactory")]
    public interface IDiscountKindFactory {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscountKindFactory/GetAllDiscountKinds", ReplyAction="http://tempuri.org/IDiscountKindFactory/GetAllDiscountKindsResponse")]
        bool GetAllDiscountKinds(out NewApp.BusinessTier.Models.DiscountKind[] DiscountKindObjArray, out string errorMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscountKindFactory/GetDiscountKind", ReplyAction="http://tempuri.org/IDiscountKindFactory/GetDiscountKindResponse")]
        bool GetDiscountKind(out NewApp.BusinessTier.Models.DiscountKind DiscountKind, out string errorMessage, int DiscountKindId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDiscountKindFactoryChannel : NewApp.DiscountKindFactorySvc.IDiscountKindFactory, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DiscountKindFactoryClient : System.ServiceModel.ClientBase<NewApp.DiscountKindFactorySvc.IDiscountKindFactory>, NewApp.DiscountKindFactorySvc.IDiscountKindFactory {
        
        public DiscountKindFactoryClient() {
        }
        
        public DiscountKindFactoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DiscountKindFactoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiscountKindFactoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiscountKindFactoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GetAllDiscountKinds(out NewApp.BusinessTier.Models.DiscountKind[] DiscountKindObjArray, out string errorMessage) {
            return base.Channel.GetAllDiscountKinds(out DiscountKindObjArray, out errorMessage);
        }
        
        public bool GetDiscountKind(out NewApp.BusinessTier.Models.DiscountKind DiscountKind, out string errorMessage, int DiscountKindId) {
            return base.Channel.GetDiscountKind(out DiscountKind, out errorMessage, DiscountKindId);
        }
    }
}
