//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewApp.SQLDataAccessFactorySvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SQLDataAccessFactorySvc.IDataAccessService")]
    public interface IDataAccessService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataAccessService/ConnectDB", ReplyAction="http://tempuri.org/IDataAccessService/ConnectDBResponse")]
        bool ConnectDB(out string errorMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataAccessService/OpenDB", ReplyAction="http://tempuri.org/IDataAccessService/OpenDBResponse")]
        bool OpenDB(out string errorMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataAccessService/CloseDB", ReplyAction="http://tempuri.org/IDataAccessService/CloseDBResponse")]
        bool CloseDB(out string closeErrorMessage, string errorMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataAccessService/ExecuteSqlNonQry", ReplyAction="http://tempuri.org/IDataAccessService/ExecuteSqlNonQryResponse")]
        bool ExecuteSqlNonQry(out string errorMessage, string SqlStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataAccessService/ExecuteSqlQry", ReplyAction="http://tempuri.org/IDataAccessService/ExecuteSqlQryResponse")]
        bool ExecuteSqlQry(out System.Data.DataSet Ds, out string errorMessage, string SqlStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataAccessService/ExecuteSPWithParamsRespDS", ReplyAction="http://tempuri.org/IDataAccessService/ExecuteSPWithParamsRespDSResponse")]
        bool ExecuteSPWithParamsRespDS(out System.Data.DataSet Ds, out string errorMessage, string StoredProcName, System.Data.SqlClient.SqlParameter[] SPParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataAccessService/ExecuteSPWithParamsNoResp", ReplyAction="http://tempuri.org/IDataAccessService/ExecuteSPWithParamsNoRespResponse")]
        bool ExecuteSPWithParamsNoResp(out string errorMessage, string StoredProcName, System.Data.SqlClient.SqlParameter[] SPParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataAccessService/ExecuteSPForSearch", ReplyAction="http://tempuri.org/IDataAccessService/ExecuteSPForSearchResponse")]
        bool ExecuteSPForSearch(out System.Data.DataSet Ds, out string errorMessage, string StoredProcName, string SearchStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataAccessService/ExecuteSPNoParamsWithRespDS", ReplyAction="http://tempuri.org/IDataAccessService/ExecuteSPNoParamsWithRespDSResponse")]
        bool ExecuteSPNoParamsWithRespDS(out System.Data.DataSet Ds, out string errorMessage, string StoredProcName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataAccessService/CheckDataAccess", ReplyAction="http://tempuri.org/IDataAccessService/CheckDataAccessResponse")]
        bool CheckDataAccess(out string errorMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataAccessService/GetNormalTable", ReplyAction="http://tempuri.org/IDataAccessService/GetNormalTableResponse")]
        System.Data.DataTable GetNormalTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataAccessService/GetNormalDataSet", ReplyAction="http://tempuri.org/IDataAccessService/GetNormalDataSetResponse")]
        bool GetNormalDataSet(out System.Data.DataSet Ds);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataAccessServiceChannel : NewApp.SQLDataAccessFactorySvc.IDataAccessService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataAccessServiceClient : System.ServiceModel.ClientBase<NewApp.SQLDataAccessFactorySvc.IDataAccessService>, NewApp.SQLDataAccessFactorySvc.IDataAccessService {
        
        public DataAccessServiceClient() {
        }
        
        public DataAccessServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataAccessServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataAccessServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataAccessServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ConnectDB(out string errorMessage) {
            return base.Channel.ConnectDB(out errorMessage);
        }
        
        public bool OpenDB(out string errorMessage) {
            return base.Channel.OpenDB(out errorMessage);
        }
        
        public bool CloseDB(out string closeErrorMessage, string errorMessage) {
            return base.Channel.CloseDB(out closeErrorMessage, errorMessage);
        }
        
        public bool ExecuteSqlNonQry(out string errorMessage, string SqlStr) {
            return base.Channel.ExecuteSqlNonQry(out errorMessage, SqlStr);
        }
        
        public bool ExecuteSqlQry(out System.Data.DataSet Ds, out string errorMessage, string SqlStr) {
            return base.Channel.ExecuteSqlQry(out Ds, out errorMessage, SqlStr);
        }
        
        public bool ExecuteSPWithParamsRespDS(out System.Data.DataSet Ds, out string errorMessage, string StoredProcName, System.Data.SqlClient.SqlParameter[] SPParameters) {
            return base.Channel.ExecuteSPWithParamsRespDS(out Ds, out errorMessage, StoredProcName, SPParameters);
        }
        
        public bool ExecuteSPWithParamsNoResp(out string errorMessage, string StoredProcName, System.Data.SqlClient.SqlParameter[] SPParameters) {
            return base.Channel.ExecuteSPWithParamsNoResp(out errorMessage, StoredProcName, SPParameters);
        }
        
        public bool ExecuteSPForSearch(out System.Data.DataSet Ds, out string errorMessage, string StoredProcName, string SearchStr) {
            return base.Channel.ExecuteSPForSearch(out Ds, out errorMessage, StoredProcName, SearchStr);
        }
        
        public bool ExecuteSPNoParamsWithRespDS(out System.Data.DataSet Ds, out string errorMessage, string StoredProcName) {
            return base.Channel.ExecuteSPNoParamsWithRespDS(out Ds, out errorMessage, StoredProcName);
        }
        
        public bool CheckDataAccess(out string errorMessage) {
            return base.Channel.CheckDataAccess(out errorMessage);
        }
        
        public System.Data.DataTable GetNormalTable() {
            return base.Channel.GetNormalTable();
        }
        
        public bool GetNormalDataSet(out System.Data.DataSet Ds) {
            return base.Channel.GetNormalDataSet(out Ds);
        }
    }
}
